---
- name: Install openssh server
  ansible.builtin.package:
    name: openssh-server
    state: present

- name: Apply config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '0644'
    owner: root
    group: root
  notify: Restart ssh

- name: Enable and start service
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: true
